Utilisateur:
  type: entity
  table: utilisateur
  id:
    id_Utilisateur:
      type: integer
      nullable: false
      options:
        unsigned: false
      id: true
      column: id
  fields:
    civilite:
      type: string
      nullable: false
      length: 256
      options:
        fixed: false
    nom:
      type: string
      nullable: false
      length: 256
      options:
        fixed: false
    prenom:
      type: string
      nullable: false
      length: 256
      options:
        fixed: false
    login:
      type: string
      nullable: false
      length: 256
      options:
        fixed: false
    email:
      type: string
      nullable: false
      length: 256
      options:
        fixed: false
    motDePasse:
      type: string
      nullable: false
      length: 256
      options:
        fixed: false
    adresse:
      type: string
      nullable: false
      length: 256
      options:
        fixed: false
    ville:
      type: string
      nullable: false
      length: 256
      options:
        fixed: false
    codePostal:
      type: string
      nullable: false
      length: 16
      options:
        fixed: false
    pays:
      type: string
      nullable: false
      length: 256
      options:
        fixed: false
    telephone:
      type: string
      nullable: false
      length: 256
      options:
        fixed: false
  lifecycleCallbacks: { }